{% set name = "rl_games" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Denys88/rl_games/archive/v{{ version }}.tar.gz
  sha256: f70429cb4c75972365362186dc7b33d90b67e543fc770b272bb812b914f44e5a
  patches:
    - 01-exclude_package_data.patch
    - 02-remove_watchdog_upper_bound.patch

build:
  noarch: python
  script:
    - rm poetry.lock pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - gym >=0.17.2
    - tensorboard >=1.14.0
    - tensorboardx >=1.6
    - pyyaml
    - psutil
    - setproctitle
    - opencv
    - wandb
    - pytorch
    - numpy
    - watchdog >=2.19

test:
  imports:
    - rl_games
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Denys88/rl_games
  summary: High performance RL library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
    - flferretti
